# Generated by Django 5.0.6 on 2024-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='nivel_dagua',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
